version: "3.8"

services:
  backend:
    build: ./reddragonai-backend
    ports:
      - "8000:8000"
    volumes:
      - ./reddragonai-backend:/app
    restart: always

  frontend:
    build: ./reddragonai-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always